### ISSUE TITLE
Data binding with angular

### ISSUE THREAD

**Issue by fedechagu** [PredixDev/px-chart#11]
I have a component that plots time series data: 

`    <px-chart>
      <px-chart-series-line
        id="timeseries-data"
        data = "{{vm.timeSeriesData}}">
      </px-chart-series-line>
    </px-chart>
`

In my controller I have:

`      this.timeSeriesData = [
        [1397102460000, 11.4403],
        [1397139660000, 13.1913],
        [1397177400000, 12.8485],
        [1397228040000, 10.975],
        [1397248260000, 12.9377],
        [1397291280000, 13.3795],
        [1397318100000, 13.0869],
        [1397342100000, 17.3758]
      ];`

I also have a socket.io client that gets new time series data every second. When I push new data into the this.timeSeriesData array, the chart does not refresh. How can I trigger the refresh or fire events in the component to make it redraw the new point?

**Comment by nonmetalhail** [comment]
Are using a standard javascript Array.push method? If so, polymer probably cannot recognize that the array has changed. Try using Polymer's array mutation methods:
https://www.polymer-project.org/1.0/docs/devguide/properties.html#array-mutation

**Comment by fedechagu** [comment]
Yes, using the standard array methods. I looked at the documentation but it only seems to work inside of polymer, so something like this:

```      removeUser: function(user) {
        var index = this.users.indexOf(user);
        this.splice('users', index, 1);
      }```

That works inside the component. But how do I call that from outside? Is there a way to extend components?

**Comment by nonmetalhail** [comment]
You should be able to access the Polymer array methods by calling the chart element.

```
var chart = document.getElementById('myChart');
chart.push('data', newPoint);
```
