### ISSUE TITLE
The "Reset Zoom" button does not appear after zooming-in.

### ISSUE THREAD

**Issue by Ishank-dubey** [PredixDev/px-chart#15]
# Submit an Issue

Hi,

Thanks for helping us improve the Predix UI platform by submitting an issue.

Before you begin, please check the list of existing issues to avoid submitting a duplicate issue.

To help us solve this issue as fast as possible, please fill out the following sections:

**Comment by nonmetalhail** [comment]
We do not see this problem. If you are still experiencing it, please provide more details and steps to reproduce and a codepen or jsfiddle demonstrating the issue.
