### ISSUE TITLE
demo links for px-chart and sub-charts do not work.

### ISSUE THREAD

**Issue by mlaymon** [PredixDev/px-chart#16]
# Submit an Issue

When on page http://predixdev.github.io/predix-ui/?show=px-chart&type=component, if I click the Demo button in the upper right, the dropdown menu remains but the rest of the page goes blank.

## Expected behavior and actual behavior:
I would expect some kind of chart to display

## Steps to reproduce the problem:
Go to URL http://predixdev.github.io/predix-ui/?show=px-chart&type=component, then click on "Demo" button in upper right.

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):
Chrome browser

## Screenshots (_optional, but very helpful_):
![blank-px-chart-demo-page](https://cloud.githubusercontent.com/assets/5920296/17636429/0164d940-60ab-11e6-9a28-4ad6f187f56b.png)

**Comment by randyaskin** [comment]
Hi @mlaymon - this site is still a work in progress and we haven't cut over to the new interactive demo layout for px-chart yet. You can still see the old working demo here, in the meantime: http://predixdev.github.io/px-chart/px-chart/index.html

**Comment by randyaskin** [comment]
New demos for px-chart has been released.
