### ISSUE TITLE
Time zone issue - time displayed in GMT rather than CET

### ISSUE THREAD

**Issue by hubertzakrzewski** [PredixDev/px-chart#17]
Is there a way to modify the display of time that seems to be displayed in GMT zone, so that it shows time in CET instead (1h ahead). Currently the time displayed in the graph is 1 hour behind so users think the graph is not up to date.
 
![time zone chart bug](https://cloud.githubusercontent.com/assets/4841379/21162074/2228d8aa-c151-11e6-9d2f-0dd1ae3f04c7.png)

**Comment by nonmetalhail** [comment]
No, I do not believe this is possible with px-chart. 

This is possible with px-vis-timeseries, which replaces px-chart: https://github.com/PredixDev/px-vis-timeseries

It is slightly complicated to specify a timezone on px-vis-timeseries, so if you decide to switch, feel free to open an issue there and I can walk you through it.
