### ISSUE TITLE
removeSeries is breaking the code

### ISSUE THREAD

**Issue by kdinluks** [PredixDev/px-chart#3]
When using the method removeSeries(seriesId) the method removes the series but breaks the code somehow.
No exception is thrown or anything but any code after the method call is not executed, not even a console.log.

Ex.:

```
if (chart.hasSeries(series.tag)) {
   console.log('Series ' + series.tag + ' detected.');
   chart.removeSeries(series.tag);
   console.log('Series ' + series.tag + ' removed.');
}
```

In this example the first log is created and the series is removed but the second log is never created.

**Comment by priyabrat1801** [comment]
Its throwing the below error in console and then blocks further action on the chart.

**Uncaught TypeError: Cannot read property 'getExtremes' of undefined**
**Uncaught TypeError: e.getAttribute is not a function**

**Comment by priyabrat1801** [comment]
This is using version 1.4.0

**Comment by iamcap** [comment]
I also got same error when I call removeSeries. 

From developer, I could identified the reason why. See attached screenshots.

![screen shot 2016-03-11 at 5 27 00 pm](https://cloud.githubusercontent.com/assets/3128338/13751247/807d888c-e9c6-11e5-8df8-5c346469f60b.png)

**Comment by nonmetalhail** [comment]
Hello, px-chart has been deprecated. Please move over to px-vis-timeseries: [https://github.com/PredixDev/px-vis-timeseries](https://github.com/PredixDev/px-vis-timeseries)
