### ISSUE TITLE
refreshAllSeries not replotting udpated series

### ISSUE THREAD

**Issue by aljacinto** [PredixDev/px-chart#4]
Just want to know if this use case for calling refreshAllSeries:  We have multiple series plotted in our chart, user changed the date range.  We retrieved the new data for the series and call updateSeries but tell it not to redraw.  After calling updateSeries for all plotted tags then call refreshAllSeries to redraw the updated series.  Is this the scenario for calling refreshAllSeries?  if not, can you give details on when to call?

Sample code:

```
        plottedTags.forEach(function(aPlottedTag) {
            chart.updateSeries(aPlottedTag.name, aPlottedTag.newData, true);
        });
        chart.refreshAllSeries();
```

Thanks,
Alex

**Comment by nonmetalhail** [comment]
Hello, px-chart has been deprecated. Please switch to px-vis-timeseries: [https://github.com/PredixDev/px-vis-timeseries](https://github.com/PredixDev/px-vis-timeseries)
