### ISSUE TITLE
px-chart-xaxis needed

### ISSUE THREAD

**Issue by Sauryanjanbhoi1** [PredixDev/px-chart#7]
1. How can we configure and update charts x-axis and its labels ?
2. Do we have a px-chart-xaxis polymer element for the same ?

Snapshot attached below:
![image](https://cloud.githubusercontent.com/assets/15339343/13617871/ea0db5b6-e5a6-11e5-8b79-62903d158bbd.png)

**Comment by KevinVecchione** [comment]
It looks like px-chart only creates a StockChart at the moment, which only supports a datetime x-axis. I used a library called misbehave (https://github.com/devinivy/misbehave) to create a behavior from px-chart. I used that behavior to create my own chart component which creates a Chart or StockChart depending on my use case. Hope that helps.

**Comment by nonmetalhail** [comment]
This is correct; px-chart is only a timeseries chart. We have released a chart that should support your need. Please see px-vis-xy-chart: http://predixdev.github.io/predix-ui/?show=px-vis-xy-chart&type=component
