### ISSUE TITLE
Y axis labels more than 4 characters/digits wrapping to next line

### ISSUE THREAD

**Issue by priyabrat1801** [PredixDev/px-chart#8]
When the y-axis label values goes beyond 4 characters/digits, its wrapping to next line. Is there any configuration params to handle this? Screen shot atatched.
![screen shot 2016-03-08 at 2 55 19 pm](https://cloud.githubusercontent.com/assets/7915828/13619461/0869045c-e53e-11e5-8912-22b2bd7545de.png)

**Comment by priyabrat1801** [comment]
Using version 1.4.0

**Comment by Sauryanjanbhoi1** [comment]
Could you please share the sample html code you are using to show it.

**Comment by priyabrat1801** [comment]
Below is the snippet for px-chart we are using:

    <px-chart id="{{chart.id}}"
            zoom-type="xy"
            height="434"
            tooltip-datetime-format="MM/DD/YY hh:mm:ss A"
            legend='{"enabled": false}'
            navigator-disabled="true"
            tooltip-kind="hc"
            margin="[45, 60, 30, 45]"
            >
        <px-chart-yaxis offset="0" id="firstAxis-{{chart.id}}" title='{"text": ""}'></px-chart-yaxis>
        <px-chart-yaxis opposite="true" offset="-2.5" title='{"text": ""}' id="secondAxis-{{chart.id}}"></px-chart-yaxis>
    </px-chart>

**Comment by Sauryanjanbhoi1** [comment]
**Try using below snippet and format using labels attribute like below:
**
1. x and y values change position of labels and format:"{value} k" will restrict your label(k) to go to next line 

<px-chart-yaxis id="firstAxis" title='{"text": "Model Class"}' labels='{"format": "{value} k", "x": 0, "y": 0 }' >
</px-chart-yaxis>

**Comment by Sauryanjanbhoi1** [comment]
Please share code snippet.

**Comment by priyabrat1801** [comment]
Here is the code i used...

              <px-chart id="{{chart.id}}"
                      zoom-type="xy"
                      height="434"
                      tooltip-datetime-format="MM/DD/YY hh:mm:ss A"
                      legend='{"enabled": false}'
                      navigator-disabled="true"
                      tooltip-kind="hc"
                      margin="[45, 60, 30, 45]">
                  <px-chart-yaxis offset="0" id="firstAxis-{{chart.id}}" title='{"text": ""}' labels='{"format": "{value} k", "x": 0, "y": 0 }'></px-chart-yaxis>
                  <px-chart-yaxis opposite="true" offset="-2.5" title='{"text": ""}' id="secondAxis-{{chart.id}}"></px-chart-yaxis>
              </px-chart>

**Comment by randyaskin** [comment]
Old issue. Px-chart is being deprecated in favor of px-vis-timeseries. Closing this issue for the time being, please try cutting over to the new component and comment there if you still have issues with axis formatting.
