### ISSUE TITLE
iron-ajax json format needs to be documented

### ISSUE THREAD

**Issue by benschenker** [PredixDev/px-chart#9]
Adding iron-ajax functionality to a chart requires a very specifically formatted JSON that is not documented anywhere.

From what I can see so far it must look like:
```
{
  "series" : [] // Data goes here!
}
```
But there are other undocumented values too.

**Comment by nonmetalhail** [comment]
The README defines these two formats:
```
// Expected data format
[
  [1397102460000, 11.4403],
  [1397139660000, 13.1913],
  [1397177400000, 12.8485],
  [1397228040000, 10.975],
  [1397248260000, 12.9377],
  [1397291280000, 13.3795],
  [1397318100000, 13.0869],
  [1397342100000, 17.3758]
]
// or
[
  {'x': 1397102460000, 'y': 11.4403},
  {'x': 1397139660000, 'y': 13.1913},
  {'x': 1397177400000, 'y': 12.8485},
  {'x': 1397228040000, 'y': 10.975},
  {'x': 1397248260000, 'y': 12.9377},
  {'x': 1397291280000, 'y': 13.3795},
  {'x': 1397318100000, 'y': 13.0869},
  {'x': 1397342100000, 'y': 17.3758}
]

```

Also, this repo has demo data who's format works: https://github.com/PredixDev/px-demo-data

What undocumented values are you seeing?

**Comment by nonmetalhail** [comment]
Closing this for now. If you feel it needs additional documentation, please let me know.
